export const golangRoutes = [
    {
        text: '入门',
        link:'/go/base/index',
        items:[
            {
                text:'01_变量和常量',
                link:'/go/base/markdown/01'
            },
            {
                text:'02_基本类型与运算符',
                link:'/go/base/markdown/02'
            },
            {
                text:'03_字符串处理',
                link:'/go/base/markdown/03'
            },
            {
                text:'04_流程控制',
                link:'/go/base/markdown/04'
            },
            {
                text:'05_数组与切片',
                link:'/go/base/markdown/05'
            },
            {
                text:'06_map',
                link:'/go/base/markdown/06'
            },
            {
                text:'07_函数',
                link:'/go/base/markdown/07'
            },
            {
                text:'08_包',
                link:'/go/base/markdown/08'
            },
            {
                text:'09_结构体',
                link:'/go/base/markdown/09'
            },
            {
                text:'10_方法',
                link:'/go/base/markdown/10'
            },
            {
                text:'11_接口',
                link:'/go/base/markdown/11'
            },
            {
                text:'12_面向对象',
                link:'/go/base/markdown/12'
            },
            {
                text:'13_反射',
                link:'/go/base/markdown/13'
            },
            {
                text:'14_读写数据',
                link:'/go/base/markdown/14'
            },
            {
                text:'15_错误处理',
                link:'/go/base/markdown/15'
            },
            {
                text:'16_并发',
                link:'/go/base/markdown/16'
            }
        ]
    },
    {
        text: '进阶',
        link:'/golang/advanced/index',
        items:[
            {
                text:'01_何为runtime',
                link:'go/thorough/markdown/01'
            },
            {
                text:"02_go程序是如何编译的",
                link:'go/thorough/markdown/02'
            },
            {
                text:"03_go程序是如何运行的",
                link:'go/thorough/markdown/03'
            },
            {
                text: "04_go语言是面向对象吗？",
                link:'go/thorough/markdown/04'
            },
            {
                text: "05_空结构体的妙用",
                link: 'go/thorough/markdown/05'
            },
            {
                text: "06_字符串",
                link:'go/thorough/markdown/06'
            }
            
        ]
    }

]